package com.lowheel.champions

import com.lowheel.enums.Role

/**
 * Conversion entre un champion et ses rôles
 */
val championRoleMap: Map<String, List<Role>> = mapOf(
    "Aatrox" to listOf(Role.TOP, Role.JUNGLE),
    "Ahri" to listOf(Role.MID),
    "Akali" to listOf(Role.MID,Role.TOP),
    "Akshan" to listOf(Role.MID,Role.TOP),
    "Alistar" to listOf(Role.SUPPORT),
    "Amumu" to listOf(Role.JUNGLE, Role.SUPPORT),
    "Anivia" to listOf(Role.MID),
    "Annie" to listOf(Role.MID),
    "Aphelios" to listOf(Role.ADC),
    "Ashe" to listOf(Role.ADC, Role.SUPPORT),
    "AurelionSol" to listOf(Role.MID),
    "Azir" to listOf(Role.MID),

    "Bard" to listOf(Role.SUPPORT),
    "BelVeth" to listOf(Role.JUNGLE),
    "Blitzcrank" to listOf(Role.SUPPORT),
    "Brand" to listOf(Role.MID, Role.SUPPORT),
    "Braum" to listOf(Role.SUPPORT),
    "Briar" to listOf(Role.JUNGLE),
    "Caitlyn" to listOf(Role.ADC),
    "Camille" to listOf(Role.TOP),
    "Cassiopeia" to listOf(Role.TOP, Role.MID),
    "ChoGath" to listOf(Role.TOP, Role.MID),

    "Corki" to listOf(Role.MID),
    "Darius" to listOf(Role.TOP),
    "Diana" to listOf(Role.MID, Role.JUNGLE),
    "DrMundo" to listOf(Role.TOP, Role.JUNGLE),
    "Draven" to listOf(Role.ADC),
    "Ekko" to listOf(Role.MID, Role.JUNGLE),
    "Elise" to listOf(Role.JUNGLE, Role.SUPPORT),
    "Evelynn" to listOf(Role.JUNGLE),
    "Ezreal" to listOf(Role.ADC),

    "Fiddlesticks" to listOf(Role.JUNGLE, Role.SUPPORT),
    "Fiora" to listOf(Role.TOP),
    "Fizz" to listOf(Role.MID),
    "Galio" to listOf(Role.MID, Role.SUPPORT),
    "Gangplank" to listOf(Role.TOP),
    "Garen" to listOf(Role.TOP),
    "Gnar" to listOf(Role.TOP),
    "Gragas" to listOf(Role.TOP, Role.JUNGLE, Role.MID, Role.SUPPORT),
    "Graves" to listOf(Role.JUNGLE),

    "Gwen" to listOf(Role.TOP, Role.JUNGLE),
    "Hecarim" to listOf(Role.JUNGLE),
    "Heimerdinger" to listOf(Role.TOP, Role.MID),
    "Hwei" to listOf(Role.MID),
    "Illaoi" to listOf(Role.TOP),
    "Irelia" to listOf(Role.TOP, Role.MID),
    "Ivern" to listOf(Role.JUNGLE),
    "Janna" to listOf(Role.SUPPORT),
    "JarvanIV" to listOf(Role.JUNGLE, Role.SUPPORT),
    "Jax" to listOf(Role.TOP, Role.JUNGLE),

    "Jayce" to listOf(Role.TOP, Role.JUNGLE, Role.MID),
    "Jhin" to listOf(Role.ADC),
    "Jinx" to listOf(Role.ADC),
    "KSante" to listOf(Role.TOP),
    "Kaisa" to listOf(Role.ADC),
    "Kalista" to listOf(Role.ADC),
    "Karma" to listOf(Role.SUPPORT, Role.MID),
    "Karthus" to listOf(Role.JUNGLE, Role.ADC),
    "Kassadin" to listOf(Role.MID),
    "Katarina" to listOf(Role.MID),
    "Kayle" to listOf(Role.TOP, Role.MID),
    "Kayn" to listOf(Role.JUNGLE),
    "Kennen" to listOf(Role.TOP, Role.MID),
    "KhaZix" to listOf(Role.JUNGLE),
    "Kindred" to listOf(Role.JUNGLE),
    "Kled" to listOf(Role.TOP),
    "KogMaw" to listOf(Role.ADC),

    "LeBlanc" to listOf(Role.MID),
    "LeeSin" to listOf(Role.JUNGLE),
    "Leona" to listOf(Role.SUPPORT),
    "Lillia" to listOf(Role.JUNGLE),
    "Lissandra" to listOf(Role.MID),
    "Lucian" to listOf(Role.ADC, Role.MID),
    "Lulu" to listOf(Role.SUPPORT),
    "Lux" to listOf(Role.MID, Role.SUPPORT),

    "Malphite" to listOf(Role.TOP, Role.JUNGLE),
    "Malzahar" to listOf(Role.MID),
    "Maokai" to listOf(Role.TOP, Role.JUNGLE, Role.SUPPORT),
    "MasterYi" to listOf(Role.JUNGLE),
    "Milio" to listOf(Role.SUPPORT),
    "MissFortune" to listOf(Role.ADC),
    "Mordekaiser" to listOf(Role.TOP),
    "Morgana" to listOf(Role.SUPPORT, Role.MID),

    "Naafiri" to listOf(Role.MID),
    "Nami" to listOf(Role.SUPPORT),
    "Nasus" to listOf(Role.TOP),
    "Nautilus" to listOf(Role.SUPPORT),
    "Neeko" to listOf(Role.MID, Role.SUPPORT),
    "Nidalee" to listOf(Role.JUNGLE),
    "Nilah" to listOf(Role.ADC),
    "Nocturne" to listOf(Role.JUNGLE),
    "Nunu" to listOf(Role.JUNGLE),

    "Olaf" to listOf(Role.TOP, Role.JUNGLE),
    "Orianna" to listOf(Role.MID),
    "Ornn" to listOf(Role.TOP),
    "Pantheon" to listOf(Role.TOP, Role.MID, Role.SUPPORT),
    "Poppy" to listOf(Role.TOP, Role.JUNGLE),
    "Pyke" to listOf(Role.SUPPORT),

    "Qiyana" to listOf(Role.MID),
    "Quinn" to listOf(Role.TOP),

    "Rakan" to listOf(Role.SUPPORT),
    "Rammus" to listOf(Role.JUNGLE),
    "RekSai" to listOf(Role.JUNGLE),
    "Rell" to listOf(Role.SUPPORT),
    "Renata" to listOf(Role.SUPPORT),
    "Renekton" to listOf(Role.TOP),
    "Rengar" to listOf(Role.JUNGLE),
    "Riven" to listOf(Role.TOP),
    "Rumble" to listOf(Role.TOP),
    "Ryze" to listOf(Role.MID),

    "Samira" to listOf(Role.ADC),
    "Sejuani" to listOf(Role.JUNGLE),
    "Senna" to listOf(Role.SUPPORT),
    "Seraphine" to listOf(Role.SUPPORT, Role.MID),
    "Sett" to listOf(Role.TOP, Role.SUPPORT),
    "Shaco" to listOf(Role.JUNGLE, Role.SUPPORT),
    "Shen" to listOf(Role.TOP, Role.SUPPORT),
    "Shyvana" to listOf(Role.JUNGLE),
    "Singed" to listOf(Role.TOP),
    "Sion" to listOf(Role.TOP),
    "Sivir" to listOf(Role.ADC),
    "Skarner" to listOf(Role.JUNGLE),
    "Smolder" to listOf(Role.ADC),
    "Sona" to listOf(Role.SUPPORT),
    "Soraka" to listOf(Role.SUPPORT),
    "Swain" to listOf(Role.TOP, Role.MID, Role.SUPPORT),
    "Sylas" to listOf(Role.MID, Role.JUNGLE),
    "Syndra" to listOf(Role.MID),

    "TahmKench" to listOf(Role.TOP, Role.SUPPORT),
    "Taliyah" to listOf(Role.MID, Role.JUNGLE),
    "Talon" to listOf(Role.MID, Role.JUNGLE),
    "Taric" to listOf(Role.SUPPORT),
    "Teemo" to listOf(Role.TOP),
    "Thresh" to listOf(Role.SUPPORT),
    "Tristana" to listOf(Role.ADC, Role.MID),
    "Trundle" to listOf(Role.TOP, Role.JUNGLE),
    "Tryndamere" to listOf(Role.TOP),
    "TwistedFate" to listOf(Role.MID),
    "Twitch" to listOf(Role.ADC),

    "Udyr" to listOf(Role.JUNGLE,Role.TOP),
    "Urgot" to listOf(Role.TOP),

    "Varus" to listOf(Role.TOP, Role.ADC, Role.MID),
    "Vayne" to listOf(Role.ADC,Role.TOP),
    "Veigar" to listOf(Role.MID),
    "VelKoz" to listOf(Role.MID, Role.SUPPORT),
    "Vex" to listOf(Role.MID),
    "Vi" to listOf(Role.JUNGLE),
    "Viego" to listOf(Role.JUNGLE),
    "Viktor" to listOf(Role.MID),
    "Vladimir" to listOf(Role.MID,Role.TOP),
    "Volibear" to listOf(Role.TOP, Role.JUNGLE),

    "Warwick" to listOf(Role.JUNGLE,Role.TOP),
    "Wukong" to listOf(Role.TOP, Role.JUNGLE),

    "Xayah" to listOf(Role.ADC),
    "Xerath" to listOf(Role.MID, Role.SUPPORT),
    "XinZhao" to listOf(Role.JUNGLE),

    "Yasuo" to listOf(Role.MID,Role.TOP),
    "Yone" to listOf(Role.MID,Role.TOP),
    "Yorick" to listOf(Role.TOP),
    "Yuumi" to listOf(Role.SUPPORT),

    "Zac" to listOf(Role.JUNGLE,Role.TOP),
    "Zed" to listOf(Role.JUNGLE, Role.MID),
    "Zeri" to listOf(Role.ADC),
    "Ziggs" to listOf(Role.MID, Role.ADC),
    "Zilean" to listOf(Role.SUPPORT, Role.MID),
    "Zoe" to listOf(Role.MID),
    "Zyra" to listOf(Role.SUPPORT)
)
